### PR TITLE
feat: add 'accessors' option

### PR DESCRIPTION
**Pull request by yanick**
I need to clean this, but that should be the answer for #196

### CODE REVIEW

**Comment by yanick** [comment]
Okay, it's now clean and, I think, ready to go.

**Review by sebastianrothe — APPROVED** [review]

**Comment by sebastianrothe** [comment]
What is missing here? How can we get "Semantic Pull Request" to be green?

**Comment by yanick** [comment]
> What is missing here? How can we get "Semantic Pull Request" to be green?

The Semantic Pull action is controlled by a project that is no longer active / working, so I don't think there is anything we (we = anybody but the true owner of the repo) can do to fix it.

BUUUUT I do have magic admin powers to at least merge the PR. I'll do so. :-)

**Comment by WbaN314** [comment]
This fix is not yet included in the latest version of the node package. Shouldn't the version be updated to 3.1.4 or am i misunderstanding?

**Comment by yanick** [comment]
It seems that merging another PR did the trick and kicked the deployment process into gears. W00t! :tada:

**Pull request merged**
