### PR TITLE
feat: set svelte context in render fn

### LINKED ISSUE #118: Specify/mock context
Hi ! My question is pretty simple:
I was wondering if there was any way to mock or pass a test context with the render function ?

### LINKED ISSUE #136: support context options?
hi 👋

as the [svelte doc](https://svelte.dev/docs#Creating_a_component). 

I haven't paid attention to the progress of the release about svelte, but it seems that context configuration is already supported. 

```js
const svleteComponentOptions = ['anchor', 'props', 'hydrate', 'intro'] // add 'context' ?
```

### PR DESCRIPTION
**Pull request by apricote**
Fixes #118
Fixes #136

## Description

Support passing the svelte component context in `componentOptions`.

[Previously one had to write a wrapper component that could set the context](https://svelte-recipes.netlify.app/testing/#testing-the-context-api).

## Usage

```svelte
<!-- Test.svelte -->
<script lang="ts">
  import { getContext } from "svelte";

  const foo = getContext("foo");

  console.log({ foo });
</script>

{foo}
```

```ts
// Test.test.ts
import { render } from "@testing-library/svelte";
import Test from "./Test.svelte";

it("gets context", () => {
  render(Test, { context: new Map([["foo", "bar"]]) });
});
```

### CODE REVIEW

**Comment by hexagonrecursion** [comment]
Please merge this. I need this. What is the roadblock?

**Comment by hexagonrecursion** [comment]
Workaround: https://svelte-recipes.netlify.app/testing/#testing-the-context-api

**Comment by cbxp** [comment]
Please merge

**Comment by sebastianrothe** [comment]
What is the problem with this PR?

**Comment by apricote** [comment]
As far as I know, there is no problem. This library just does not seem to be actively maintained. I previously asked for a review in the Discord channel, but got no answer there either.

**Comment by sebastianrothe** [comment]
Okay, can someone from the maintainers add (@apricote or @yanick), so we can proceed? @benmccann 

Referencing #182 as well, because it has some tests in it.

**Comment by yanick** [comment]
For what it's worth, if we want to go with this PR, I'm totally game to rebase my tests on it.

**Comment by sebastianrothe** [comment]
> For what it's worth, if we want to go with this PR, I'm totally game to rebase my tests on it.

Nah, your PR is the same with tests included. Your PR should be favored. This one should be closed. Also this one here is out of date.

**Comment by apricote** [comment]
Closing in favor of #182 that also includes test for the functionality.

**Comment by sebastianrothe** [comment]
Thank you :)

**Pull request closed without merging**
