### PR TITLE
chore: remove invalid eslint rule

### PR DESCRIPTION
**Pull request by mihar-22**

### CODE REVIEW

**Review by benmonro — APPROVED** [review]

**Comment by mihar-22** [comment]
Hey @benmonro! Hope you're doing well. Is our CI busted? Jobs get queued but nothing happens, any ideas?

**Comment by benmonro** [comment]
@mihar-22 yeah Travis has switched to some new model I think. I've switched all my other projects to use GitHub actions.

**Comment by mihar-22** [comment]
Okay cool I guess I'll update this library when I have some time, I've also been using GitHub Actions in my projects, super clean.

**Comment by benmonro** [comment]
I think this was resolved in another pr  If not feel free to reopen

**Pull request closed without merging**
